[2024-06-18T18:30:39.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:30:39.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:30:39.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:30:39.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:30:39.291+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:30:39.313+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:30:39.307+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpha9i0716']
[2024-06-18T18:30:39.315+0000] {standard_task_runner.py:91} INFO - Job 191: Subtask snowflake_copy_scores
[2024-06-18T18:30:39.315+0000] {standard_task_runner.py:63} INFO - Started process 15341 to run task
[2024-06-18T18:30:39.439+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:30:39.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:30:39.707+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:30:39.740+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (TYPE = 'JSON');
        
[2024-06-18T18:30:39.797+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:30:40.351+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:30:40.354+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:30:40.355+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:30:40.662+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:40.663+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:30:40.725+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:30:40.725+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:30:40.726+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:30:40.726+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518d6-0001-e497-0006-023e0001d10e
[2024-06-18T18:30:40.726+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (TYPE = 'JSON');, parameters: None
[2024-06-18T18:30:40.823+0000] {connection.py:762} INFO - closed
[2024-06-18T18:30:40.866+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:30:40.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:30:40.919+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b518d6-0001-e498-0006-023e0001b17a: SQL compilation error:
Stage 'NBA_STATS_ANALYTICS.NBA_STATS.SNOW_S3_STAGE' does not exist or not authorized.
[2024-06-18T18:30:40.943+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T183039, end_date=20240618T183040
[2024-06-18T18:30:40.958+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 191 for task snowflake_copy_scores (002003 (02000): 01b518d6-0001-e498-0006-023e0001b17a: SQL compilation error:
Stage 'NBA_STATS_ANALYTICS.NBA_STATS.SNOW_S3_STAGE' does not exist or not authorized.; 15341)
[2024-06-18T18:30:40.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:30:41.016+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:30:41.018+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:41:39.490+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:41:39.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:41:39.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:41:39.556+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:41:39.577+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:41:39.597+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18906) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:41:39.601+0000] {standard_task_runner.py:63} INFO - Started process 19015 to run task
[2024-06-18T18:41:39.599+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpb5t3jcmt']
[2024-06-18T18:41:39.603+0000] {standard_task_runner.py:91} INFO - Job 213: Subtask snowflake_copy_scores
[2024-06-18T18:41:39.751+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:41:40.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:41:40.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:41:40.029+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (TYPE = 'JSON');
        
[2024-06-18T18:41:40.071+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:41:40.427+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:41:40.430+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:41:40.431+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:41:40.861+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:40.861+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:41:40.925+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:41:40.925+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:41:40.925+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:41:40.926+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518e1-0001-e364-0006-023e0001e112
[2024-06-18T18:41:40.926+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (TYPE = 'JSON');, parameters: None
[2024-06-18T18:41:41.194+0000] {connection.py:762} INFO - closed
[2024-06-18T18:41:41.222+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:41:41.253+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:41:41.254+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b518e1-0001-e364-0006-023e0001e116: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T18:41:41.278+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T184139, end_date=20240618T184141
[2024-06-18T18:41:41.290+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 213 for task snowflake_copy_scores (002019 (0A000): 01b518e1-0001-e364-0006-023e0001e116: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 19015)
[2024-06-18T18:41:41.308+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:41:41.340+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:41:41.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:54:32.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:54:32.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:54:32.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:54:32.234+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T18:54:32.248+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:54:32.261+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=23163) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:54:32.262+0000] {standard_task_runner.py:63} INFO - Started process 23186 to run task
[2024-06-18T18:54:32.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpigys5twx']
[2024-06-18T18:54:32.267+0000] {standard_task_runner.py:91} INFO - Job 232: Subtask snowflake_copy_scores
[2024-06-18T18:54:32.364+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:54:32.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:54:32.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:54:32.670+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T18:54:32.703+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:54:32.981+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:54:32.982+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:54:32.985+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:54:33.425+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:33.426+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:54:33.502+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:54:33.502+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:54:33.505+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:54:33.508+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518ee-0001-e496-0006-023e00019226
[2024-06-18T18:54:33.509+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T18:54:33.785+0000] {connection.py:762} INFO - closed
[2024-06-18T18:54:33.816+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:54:33.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:54:33.878+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b518ee-0001-e49c-0006-023e00017266: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T18:54:33.920+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T185432, end_date=20240618T185433
[2024-06-18T18:54:33.936+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 232 for task snowflake_copy_scores (002019 (0A000): 01b518ee-0001-e49c-0006-023e00017266: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 23186)
[2024-06-18T18:54:33.973+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:54:34.005+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:54:34.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T19:10:00.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T19:10:00.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:10:00.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:10:00.445+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T19:10:00.471+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T19:10:00.494+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpmiheyztc']
[2024-06-18T19:10:00.500+0000] {standard_task_runner.py:91} INFO - Job 251: Subtask snowflake_copy_scores
[2024-06-18T19:10:00.505+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29571) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T19:10:00.509+0000] {standard_task_runner.py:63} INFO - Started process 29606 to run task
[2024-06-18T19:10:00.657+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T19:10:00.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T19:10:00.890+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T19:10:00.917+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T19:10:00.978+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:10:01.300+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:10:01.305+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T19:10:01.306+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T19:10:01.306+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:10:01.420+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:10:01.690+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:10:01.693+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T19:10:01.755+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:10:01.756+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T19:10:01.756+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T19:10:01.757+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518fe-0001-e49a-0006-023e0001a256
[2024-06-18T19:10:01.757+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T19:10:01.918+0000] {connection.py:762} INFO - closed
[2024-06-18T19:10:01.946+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T19:10:01.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T19:10:01.988+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b518fe-0001-e49c-0006-023e0001727a: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T19:10:02.013+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T191000, end_date=20240618T191002
[2024-06-18T19:10:02.025+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 251 for task snowflake_copy_scores (002019 (0A000): 01b518fe-0001-e49c-0006-023e0001727a: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 29606)
[2024-06-18T19:10:02.065+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T19:10:02.097+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T19:10:02.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T20:33:20.838+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T20:33:20.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:33:20.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:33:20.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T20:33:21.022+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T20:33:21.053+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpkkyztned']
[2024-06-18T20:33:21.068+0000] {standard_task_runner.py:91} INFO - Job 283: Subtask snowflake_copy_scores
[2024-06-18T20:33:21.067+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2823) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T20:33:21.069+0000] {standard_task_runner.py:63} INFO - Started process 2885 to run task
[2024-06-18T20:33:21.251+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T20:33:21.534+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T20:33:21.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T20:33:21.570+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T20:33:21.618+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:33:22.032+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:33:22.034+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T20:33:22.036+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T20:33:22.036+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:33:22.144+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:33:22.424+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:22.425+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T20:33:22.499+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:33:22.500+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T20:33:22.501+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T20:33:22.501+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51951-0001-e49a-0006-023e0001a2c2
[2024-06-18T20:33:22.501+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T20:33:22.803+0000] {connection.py:762} INFO - closed
[2024-06-18T20:33:22.837+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T20:33:22.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T20:33:22.892+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b51951-0001-e495-0006-023e0001823a: SQL compilation error:
File format 'JSON_FORMAT' does not exist or not authorized.
[2024-06-18T20:33:22.920+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T203320, end_date=20240618T203322
[2024-06-18T20:33:22.942+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 283 for task snowflake_copy_scores (002003 (02000): 01b51951-0001-e495-0006-023e0001823a: SQL compilation error:
File format 'JSON_FORMAT' does not exist or not authorized.; 2885)
[2024-06-18T20:33:22.990+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T20:33:23.025+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T20:33:23.027+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
